### ISSUE TITLE
Cancelation support

### ISSUE THREAD

**Issue by jherby2k** [nnic/google_home_timers_card#1]
Thanks for your updates to this card! Wondering if you'd take a request...

**Describe the solution you'd like**
Id like to be able to cancel a timer (or alarm i suppose) by clicking an X beside it

**Describe alternatives you've considered**
This is doable by calling a service like this:
```yaml
service: google_home.delete_timer
data:
  entity_id: sensor.kitchen_timers
  timer_id: timer/47dc1fa0-5ec0-2cc7-9ead-a94b85e22769
```
Problem is getting the timer_id from the timer i'm clicking on. So i think it would have to be integrated into this card. My skills in this area are non-existent :(
