### ISSUE TITLE
hidden cards

### ISSUE THREAD

**Issue by jherby2k** [nnic/google_home_timers_card#2]
**Describe the bug**
when using hideCardIfNoAlarmOrTimers or hideInactiveTimers, if a new timer is created, it doesn't display unless you refresh the view.

**To Reproduce**
1. Set hideCardIfNoAlarmOrTimers=true, or hideInactiveTimers=true
2. Leave the dashboard open
3. Start a timer, and confirm the entity is updated
4. No timer is displayed
5. Hit refresh/F5
6. Timer is displayed

**Expected behavior**
Automatically refreshes when the entity state changes

**Comment by jherby2k** [comment]
Timers also don't disappear after running down until you refresh, but i'm okay with that.

Sorry to dump a bug report on ya but any help appreciated!

**Comment by jherby2k** [comment]
I've found a workaround using config-template-card, if you're curious.

```yaml
type: custom:config-template-card
entities:
  - sensor.office_speaker_timers
element:
  type: custom:googlehome-card-new
  timerEntity: sensor.office_speaker_timers
  name: Office
  hideCardIfNoAlarmOrTimers: true
```

This works because config-template-card watches the entities under "entities" for changes, and then refreshes itself.
